version: '3.8' 
services: 
  web: 
    image: nlpappu/myrepo:pyweb
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
  my-db: 
    image: "redis:alpine"
    ports: 
    - "6379:6379"
    volumes:
    - .:/data
